### ISSUE TITLE
show an error when adding an inexistant currency

### ISSUE THREAD

**Issue by rpesche** [rpesche/cryptopcash#1]
If an invalid currency is added to cryptopcash, the application crash and an exception is raised.

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/romain/cryptopcash/cryptopcash/__main__.py", line 5, in <module>
    main()
  File "/home/romain/cryptopcash/cryptopcash/cryptopcash.py", line 76, in main
    cryptopcash.start_cryptopcash()
  File "/home/romain/cryptopcash/cryptopcash/cryptopcash.py", line 41, in start_cryptopcash
    self.main_ui.run()
  File "/home/romain/cryptopcash/cryptopcash/ui/Main.py", line 49, in run
    self.loop.run()
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/container.py", line 595, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/decoration.py", line 837, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/wimp.py", line 540, in keypress
    self._emit('click')
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/widget.py", line 460, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/home/romain/cryptopcash/cryptopcash/ui/AddHoldingDialog.py", line 30, in add_holding
    coin = context.get_coin_info(symbol)
  File "/home/romain/cryptopcash/cryptopcash/cryptopcash.py", line 59, in get_coin_info
    return c.get_coin_info(symbol)
  File "/home/romain/cryptopcash/cryptopcash/market/CryptoCompare.py", line 18, in get_coin_info
    infos = cryptocompy_coin.get_coin_list(coins=symbol)
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/cryptocompy/coin.py", line 51, in get_coin_list
    data = {c: data[c] for c in coins}
  File "/home/romain/.local/share/virtualenvs/cryptopcash/lib/python3.6/site-packages/cryptocompy/coin.py", line 51, in <dictcomp>
    data = {c: data[c] for c in coins}
KeyError: 'aente'
```

We need to catch this exception and show a message to the user.

**Comment by rpesche** [comment]
resolved with 1.2.0
